dataset = [
    # Joy
    {"text": "Я так счастлив сегодня!", "label": "joy"},
    {"text": "Как же здорово всё получилось!", "label": "joy"},
    {"text": "Я получил подарок!", "label": "joy"},
    {"text": "Сегодня лучший день!", "label": "joy"},
    {"text": "Я в восторге от концерта", "label": "joy"},
    {"text": "Мечта сбылась!", "label": "joy"},
    {"text": "Как приятно быть дома", "label": "joy"},
    {"text": "Меня повысили на работе", "label": "joy"},
    {"text": "У меня отличные новости!", "label": "joy"},
    {"text": "Это было невероятно круто!", "label": "joy"},
    {"text": "Люблю такие моменты", "label": "joy"},
    {"text": "Мы отлично провели время", "label": "joy"},
    {"text": "Так весело было сегодня!", "label": "joy"},
    {"text": "Я наконец-то сдал экзамен!", "label": "joy"},
    {"text": "Солнце светит и я улыбаюсь", "label": "joy"},
    {"text": "Приятно получать признание", "label": "joy"},
    {"text": "Я чувствую вдохновение", "label": "joy"},
    {"text": "Всё идет как надо!", "label": "joy"},
    {"text": "Я горжусь собой", "label": "joy"},
    {"text": "Просто супер настроение!", "label": "joy"},
    {"text": "Это был незабываемый вечер", "label": "joy"},
    {"text": "Я получил комплимент", "label": "joy"},
    {"text": "Как приятно быть любимым", "label": "joy"},
    {"text": "Я смеялся весь день", "label": "joy"},
    {"text": "Люблю такие сюрпризы", "label": "joy"},
    # Sadness
    {"text": "Мне очень грустно", "label": "sadness"},
    {"text": "Я одинок", "label": "sadness"},
    {"text": "Сегодня был тяжёлый день", "label": "sadness"},
    {"text": "Мне не хватает поддержки", "label": "sadness"},
    {"text": "Я чувствую пустоту", "label": "sadness"},
    {"text": "Слёзы текут сами по себе", "label": "sadness"},
    {"text": "Я потерял друга", "label": "sadness"},
    {"text": "Ничего не радует", "label": "sadness"},
    {"text": "Мне больно вспоминать", "label": "sadness"},
    {"text": "Я скучаю по тебе", "label": "sadness"},
    {"text": "Мне не с кем поговорить", "label": "sadness"},
    {"text": "Я чувствую себя подавленным", "label": "sadness"},
    {"text": "Кажется, всё рушится", "label": "sadness"},
    {"text": "Так тяжело на душе", "label": "sadness"},
    {"text": "Я чувствую себя никому не нужным", "label": "sadness"},
    {"text": "Никто меня не понимает", "label": "sadness"},
    {"text": "Хочу просто исчезнуть", "label": "sadness"},
    {"text": "Сердце разбито", "label": "sadness"},
    {"text": "Мне не хватает сил", "label": "sadness"},
    {"text": "Я устал от всего", "label": "sadness"},
    {"text": "Ничего не хочется делать", "label": "sadness"},
    {"text": "Я потерял мотивацию", "label": "sadness"},
    {"text": "Всё кажется бессмысленным", "label": "sadness"},
    {"text": "Это так несправедливо", "label": "sadness"},
    {"text": "Мне просто плохо", "label": "sadness"},
    # Anger
    {"text": "Я злюсь!", "label": "anger"},
    {"text": "Как же это бесит!", "label": "anger"},
    {"text": "Почему всё так раздражает?", "label": "anger"},
    {"text": "Ты меня вывел из себя", "label": "anger"},
    {"text": "Я в ярости", "label": "anger"},
    {"text": "Хватит это терпеть!", "label": "anger"},
    {"text": "Я больше не могу молчать", "label": "anger"},
    {"text": "Это просто наглость", "label": "anger"},
    {"text": "Меня взбесила эта ситуация", "label": "anger"},
    {"text": "Такого хамства я не прощу", "label": "anger"},
    {"text": "Как можно быть таким тупым?", "label": "anger"},
    {"text": "Мне надоело повторять одно и то же", "label": "anger"},
    {"text": "Опять всё испортил!", "label": "anger"},
    {"text": "Я готов взорваться", "label": "anger"},
    {"text": "Разозлили с самого утра", "label": "anger"},
    {"text": "Меня никто не слушает!", "label": "anger"},
    {"text": "Это выходит за рамки", "label": "anger"},
    {"text": "У меня нет терпения на это", "label": "anger"},
    {"text": "Почему они такие безответственные?", "label": "anger"},
    {"text": "Я в бешенстве!", "label": "anger"},
    {"text": "Это последняя капля", "label": "anger"},
    {"text": "Ты серьёзно сейчас?", "label": "anger"},
    {"text": "Как можно так поступать?", "label": "anger"},
    {"text": "Они снова всё перепутали!", "label": "anger"},
    {"text": "Достали уже!", "label": "anger"},
    # Surprise
    {"text": "Ого, не ожидал такого!", "label": "surprise"},
    {"text": "Что? Правда?", "label": "surprise"},
    {"text": "Вау, вот это поворот!", "label": "surprise"},
    {"text": "Серьёзно? Это неожиданно", "label": "surprise"},
    {"text": "Я в шоке!", "label": "surprise"},
    {"text": "Вот это новость", "label": "surprise"},
    {"text": "Удивительно!", "label": "surprise"},
    {"text": "Я такого точно не ждал", "label": "surprise"},
    {"text": "Что за неожиданность!", "label": "surprise"},
    {"text": "Как такое возможно?", "label": "surprise"},
    {"text": "Ничего себе!", "label": "surprise"},
    {"text": "Это случилось внезапно", "label": "surprise"},
    {"text": "Вот это да!", "label": "surprise"},
    {"text": "Я не знал, что так можно", "label": "surprise"},
    {"text": "Это произошло так быстро", "label": "surprise"},
    {"text": "Невероятно!", "label": "surprise"},
    {"text": "Это шутка?", "label": "surprise"},
    {"text": "Ты меня удивил", "label": "surprise"},
    {"text": "Вот это подарок!", "label": "surprise"},
    {"text": "Я чуть со стула не упал", "label": "surprise"},
    {"text": "Как это получилось?", "label": "surprise"},
    {"text": "Я не верю своим глазам", "label": "surprise"},
    {"text": "Это было непредсказуемо", "label": "surprise"},
    {"text": "Ты серьёзно?", "label": "surprise"},
    {"text": "Ну ничего себе!", "label": "surprise"},
]
